"""Tests for importing Claude Code and Codex CLI sessions. All sessions are made up."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from chatlore.chunking import chunk_conversation
from chatlore.importers import ImportIssue, get_importer
from chatlore.importers.agents import TOOL_TEXT_LIMIT, session_kind
from chatlore.importers.intake import Intake
from chatlore.models import Conversation, PartType, Role, SourceKind

SESSION = "5d1f0a6e-0000-4000-8000-000000000001"


def _write(path: Path, records: list[dict[str, Any]]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(json.dumps(record) + "\n" for record in records), encoding="utf-8")
    return path


def _record(uuid: str, parent: str | None, kind: str, content: Any, **extra: Any) -> dict[str, Any]:
    message: dict[str, Any] = {"role": kind, "content": content}
    if "api_id" in extra:
        message["id"] = extra.pop("api_id")
        message["model"] = "claude-sonnet-5-5"
    return {
        "type": kind,
        "uuid": uuid,
        "parentUuid": parent,
        "sessionId": SESSION,
        "timestamp": f"2026-09-0{min(int(uuid[1:]), 9)}T10:00:00.000Z",
        "cwd": "/home/maya/tidewater",
        "gitBranch": "main",
        "isSidechain": False,
        "message": message,
        **extra,
    }


def _claude_code_session() -> list[dict[str, Any]]:
    return [
        {"type": "custom-title", "customTitle": "Add tide alerts", "sessionId": SESSION},
        _record("u1", None, "user", "Add a push alert when the morning tide is high."),
        _record(
            "u2", "u1", "assistant", [{"type": "thinking", "thinking": "hidden"}], api_id="msg_1"
        ),
        _record(
            "u3",
            "u2",
            "assistant",
            [{"type": "text", "text": "I'll look at the scheduler first."}],
            api_id="msg_1",
        ),
        _record(
            "u4",
            "u3",
            "assistant",
            [{"type": "tool_use", "id": "t1", "name": "Read", "input": {"path": "jobs.py"}}],
            api_id="msg_1",
        ),
        _record(
            "u5",
            "u4",
            "user",
            [{"type": "tool_result", "tool_use_id": "t1", "content": "x" * (TOOL_TEXT_LIMIT + 50)}],
        ),
        _record("u6", "u5", "user", "<command-name>/compact</command-name>", isMeta=False),
        _record("u7", "u6", "user", "Caveat: generated by a local command.", isMeta=True),
        _record(
            "u8",
            "u7",
            "assistant",
            [{"type": "text", "text": "Side quest."}],
            api_id="msg_9",
            isSidechain=True,
        ),
        _record(
            "u9",
            "u7",
            "assistant",
            [{"type": "text", "text": "Done: alerts go out at 6am when the tide is high."}],
            api_id="msg_2",
        ),
    ]


def _parse(kind: SourceKind, path: Path) -> tuple[list[Conversation], list[ImportIssue]]:
    issues: list[ImportIssue] = []
    return list(get_importer(kind.value).parse(path, issues.append)), issues


def test_a_claude_code_session_keeps_what_was_said_and_shortens_the_tools(tmp_path: Path) -> None:
    path = _write(tmp_path / "projects" / "tidewater" / f"{SESSION}.jsonl", _claude_code_session())

    (conversation,), issues = _parse(SourceKind.CLAUDE_CODE, path)
    branch = conversation.linear_messages()

    assert issues == []
    assert conversation.source is SourceKind.CLAUDE_CODE
    assert conversation.external_id == SESSION
    assert conversation.title == "Add tide alerts"
    assert conversation.metadata == {"project": "/home/maya/tidewater", "git_branch": "main"}
    assert [message.role for message in branch] == [
        Role.USER,
        Role.ASSISTANT,
        Role.TOOL,
        Role.ASSISTANT,
    ]
    assistant = branch[1]
    assert [part.type for part in assistant.content] == [PartType.TEXT, PartType.OTHER]
    assert assistant.content[1].text.startswith("[tool call: Read]\n")
    assert assistant.model == "claude-sonnet-5-5"
    assert "more characters]" in branch[2].text and len(branch[2].text) < TOOL_TEXT_LIMIT + 100
    assert branch[3].text == "Done: alerts go out at 6am when the tide is high."
    assert "hidden" not in json.dumps(conversation.model_dump(mode="json"))
    assert "Side quest" not in json.dumps(conversation.model_dump(mode="json"))


def test_only_what_was_said_is_chunked(tmp_path: Path) -> None:
    path = _write(tmp_path / f"{SESSION}.jsonl", _claude_code_session())
    (conversation,), _ = _parse(SourceKind.CLAUDE_CODE, path)

    texts = [chunk.text for chunk in chunk_conversation(conversation)]

    assert texts == [
        "Add a push alert when the morning tide is high.",
        "I'll look at the scheduler first.",
        "Done: alerts go out at 6am when the tide is high.",
    ]


def test_a_compacted_claude_code_session_stays_one_branch(tmp_path: Path) -> None:
    records = [
        _record("u1", None, "user", "Start the migration."),
        _record("u2", "u1", "assistant", [{"type": "text", "text": "Started."}], api_id="m1"),
        {
            "type": "system",
            "uuid": "u3",
            "parentUuid": None,
            "logicalParentUuid": "u2",
            "sessionId": SESSION,
            "subtype": "compact_boundary",
        },
        _record("u4", "u3", "user", "Now finish it."),
    ]
    path = _write(tmp_path / f"{SESSION}.jsonl", records)

    (conversation,), _ = _parse(SourceKind.CLAUDE_CODE, path)

    assert [m.text for m in conversation.linear_messages()] == [
        "Start the migration.",
        "Started.",
        "Now finish it.",
    ]


def test_a_session_with_nothing_said_is_reported(tmp_path: Path) -> None:
    records = [_record("u1", None, "assistant", [{"type": "text", "text": "x"}], isSidechain=True)]
    path = _write(tmp_path / f"{SESSION}.jsonl", records)

    conversations, issues = _parse(SourceKind.CLAUDE_CODE, path)

    assert conversations == []
    assert issues == [ImportIssue(f"{SESSION}.jsonl", "no messages")]


def _codex_session() -> list[dict[str, Any]]:
    def line(kind: str, payload: dict[str, Any], minute: int) -> dict[str, Any]:
        return {
            "timestamp": f"2026-09-10T09:{minute:02d}:00.000Z",
            "type": kind,
            "payload": payload,
        }

    def message(role: str, kind: str, text: str) -> dict[str, Any]:
        return {"type": "message", "role": role, "content": [{"type": kind, "text": text}]}

    return [
        line("session_meta", {"id": "codex-1", "cwd": "/home/maya/kayak", "cli_version": "0.9"}, 0),
        line(
            "response_item",
            message("user", "input_text", "<environment_context>cwd</environment_context>"),
            1,
        ),
        line(
            "response_item", message("user", "input_text", "Why does the swell chart lag a day?"), 2
        ),
        line(
            "event_msg",
            {"type": "user_message", "message": "Why does the swell chart lag a day?"},
            2,
        ),
        line("response_item", {"type": "reasoning", "summary": [], "encrypted_content": "zzz"}, 3),
        line(
            "response_item", message("assistant", "output_text", "Let me check the fetch job."), 4
        ),
        line(
            "response_item",
            {
                "type": "function_call",
                "name": "shell",
                "call_id": "c1",
                "arguments": json.dumps({"command": ["rg", "fetch"]}),
            },
            5,
        ),
        line(
            "response_item",
            {
                "type": "function_call_output",
                "call_id": "c1",
                "output": json.dumps({"output": "jobs/fetch.py:12", "metadata": {}}),
            },
            6,
        ),
        line(
            "response_item",
            message("assistant", "output_text", "The job reads yesterday's file."),
            7,
        ),
    ]


def test_a_codex_session_keeps_what_was_said_and_the_tools(tmp_path: Path) -> None:
    path = _write(
        tmp_path / "sessions" / "2026" / "09" / "10" / "rollout-1.jsonl", _codex_session()
    )

    (conversation,), issues = _parse(SourceKind.CODEX, path.parents[3])
    branch = conversation.linear_messages()

    assert issues == []
    assert conversation.external_id == "codex-1"
    assert conversation.title == "Why does the swell chart lag a day?"
    assert conversation.metadata == {"project": "/home/maya/kayak"}
    assert [message.role for message in branch] == [
        Role.USER,
        Role.ASSISTANT,
        Role.TOOL,
        Role.ASSISTANT,
    ]
    assert branch[1].content[1].text.startswith("[tool call: shell]\n")
    assert branch[2].text == "[tool result]\njobs/fetch.py:12"
    assert "environment_context" not in branch[0].text
    assert "zzz" not in json.dumps(conversation.model_dump(mode="json"))


def test_the_first_codex_format_is_read_too(tmp_path: Path) -> None:
    records: list[dict[str, Any]] = [
        {"id": "codex-old", "timestamp": "2025-05-01T10:00:00Z", "instructions": None},
        {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "Hi"}]},
        {"record_type": "state"},
        {
            "type": "message",
            "role": "assistant",
            "content": [{"type": "output_text", "text": "Hello"}],
        },
    ]
    path = _write(tmp_path / "rollout-old.jsonl", records)

    (conversation,), _ = _parse(SourceKind.CODEX, path)

    assert conversation.external_id == "codex-old"
    assert [m.text for m in conversation.messages] == ["Hi", "Hello"]


def test_sessions_are_recognised_by_their_records(tmp_path: Path) -> None:
    claude_code = _write(tmp_path / "a.jsonl", _claude_code_session())
    codex = _write(tmp_path / "b.jsonl", _codex_session())
    data = _write(tmp_path / "c.jsonl", [{"type": "user", "name": "not a session"}])

    assert session_kind(claude_code) is SourceKind.CLAUDE_CODE
    assert session_kind(codex) is SourceKind.CODEX
    assert session_kind(data) is None


def test_intake_imports_a_folder_of_sessions_next_to_other_files(tmp_path: Path) -> None:
    folder = tmp_path / "dropped"
    _write(folder / "claude" / f"{SESSION}.jsonl", _claude_code_session())
    _write(folder / "codex" / "rollout-1.jsonl", _codex_session())
    _write(folder / "events.jsonl", [{"event": "signup", "plan": "pro"}])
    workdir = tmp_path / "work"
    workdir.mkdir()

    intake = Intake(workdir)
    intake.scan([folder])
    found = list(intake.conversations())

    assert sorted(conversation.source.value for conversation in found) == [
        "claude_code",
        "codex",
        "document",
    ]
    assert intake.sources == {"claude_code": 1, "codex": 1, "document": 1}


def test_an_unknown_source_name_lists_the_session_importers() -> None:
    with pytest.raises(Exception, match="claude_code, codex"):
        get_importer("cursor")
